plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management'
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

apply from: '../models-plugin.gradle'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    runtimeOnly 'com.h2database:h2'
    
    // Core library must use compileOnly so it doesn't leak its models.jar to projects
    compileOnly files("${buildDir}/generated-models/models.jar")
}

compileJava {
    dependsOn modelsJar
    classpath += files(modelsJar.archiveFile)
}
