plugins {
    id 'java-gradle-plugin'
}

repositories {
    mavenCentral()
}

gradlePlugin {
    plugins {
        modelsGenerator {
            id = 'id.adiputera.models-generator'
            implementationClass = 'id.adiputera.demo.cms.generator.plugin.ModelsGeneratorPlugin'
        }
    }
}

dependencies {
    implementation gradleApi()
    implementation 'org.yaml:snakeyaml:2.2'
    implementation 'org.freemarker:freemarker:2.3.32'
}
